name: Check branch
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check-branch:
    name: Check Branch Types
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR to 'main' not from 'dev' branch
        run: exit 1
        if: github.head_ref != 'dev'
